### ISSUE TITLE
makefs error

### ISSUE THREAD

**Issue by aikchar** [cperciva/freebsd-ERL-build#4]
Ran into this error: ``makefs: `/home/vagrant/ERLBUILD.2y7e19vi/tree' size of 1120960512 is larger than the maxsize of 964689920.``

    vagrant@freebsd12current:~/freebsd-ERL-build % git rev-parse  HEAD
    b0422d6725f30f3dc0895b2300585a4b3a4253ec

Diff to fix the issue.

    vagrant@freebsd12current:~/freebsd-ERL-build % git diff
    diff --git a/buildimg.sh b/buildimg.sh
    index 517a589..4c9fe66 100644
    --- a/buildimg.sh
    +++ b/buildimg.sh
    @@ -163,7 +163,7 @@ mdconfig -d -u ${mddev}

    # Create UFS filesystem
    echo "/dev/da0s2a / ufs rw 1 1" > ${WORKDIR}/tree/etc/fstab
    -makefs -f 16384 -B big -s 920m ${WORKDIR}/UFS.img ${WORKDIR}/tree
    +makefs -f 16384 -B big -s 2500m ${WORKDIR}/UFS.img ${WORKDIR}/tree

    # Create complete disk image
    mkimg -s mbr           \

I just randomly picked a large enough size and the build completed successfully. Haven't tried the image on hardware yet.

<details>

    Updating FreeBSD repository catalogue...
    pkg: Repository FreeBSD load error: access repo file(/var/db/pkg/repo-FreeBSD.sqlite) failed: No such file or directory
    Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
    Fetching packagesite.txz: 100%    3 MiB   3.3MB/s    00:01
    Processing entries: 100%
    FreeBSD repository update completed. 15503 packages processed.
    All repositories are up to date.
    The following 5 package(s) will be affected (of 0 checked):

    New packages to be INSTALLED:
            pkg: 1.10.1
            djbdns: 1.05_21,1
            isc-dhcp43-server: 4.3.5
            ucspi-tcp: 0.88_2
            daemontools: 0.76_18

    Number of packages to be installed: 5

    The process will require 20 MiB more space.
    3 MiB to be downloaded.
    [1/5] Fetching pkg-1.10.1.txz: 100%    2 MiB   2.0MB/s    00:01
    [2/5] Fetching djbdns-1.05_21,1.txz: 100%  150 KiB 153.5kB/s    00:01
    [3/5] Fetching isc-dhcp43-server-4.3.5.txz: 100%  889 KiB 910.8kB/s    00:01
    [4/5] Fetching ucspi-tcp-0.88_2.txz: 100%   70 KiB  72.0kB/s    00:01
    [5/5] Fetching daemontools-0.76_18.txz: 100%   59 KiB  60.3kB/s    00:01
    Checking integrity... done (0 conflicting)
    /home/vagrant/ERLBUILD.2y7e19vi/FAT32.img: 66512 sectors in 66512 FAT32 clusters (512 bytes/cluster)
    BytesPerSec=512 SecPerClust=1 ResSectors=32 FATs=2 Media=0xf0 SecPerTrack=63 Heads=255 HiddenSecs=0 HugeSectors=67584 FATsecs=520 RootCluster=2 FSInfo=1 $
    ackup=2
    makefs: `/home/vagrant/ERLBUILD.2y7e19vi/tree' size of 1120960512 is larger than the maxsize of 964689920.

FreeBSD source info:

    vagrant@freebsd12current:~/src % svnlite info
    Path: .
    Working Copy Root Path: /home/vagrant/src
    URL: svn://svn.freebsd.org/base/head
    Relative URL: ^/head
    Repository Root: svn://svn.freebsd.org/base
    Repository UUID: ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f
    Revision: 316803
    Node Kind: directory
    Schedule: normal
    Last Changed Author: cem
    Last Changed Rev: 316803
    Last Changed Date: 2017-04-14 00:45:09 +0000 (Fri, 14 Apr 2017)

</details>

**Comment by cperciva** [comment]
Thanks, I've bumped the filesystem size up by another 500 MB.  The image won't fit onto 1 GB USB disks any more, but I don't think that's a problem.
